services:
  sample-java-app-dev:
    image: localhost:5000/sample-java-app:${IMAGE_TAG}
    container_name: sample-java-app-dev
    ports:
      - "8081:8080"
    environment:
      APP_ENV: dev
      APP_BRANCH: ${APP_BRANCH}
      APP_IMAGE_TAG: ${IMAGE_TAG}
    restart: unless-stopped