pipeline {
    agent any

    environment {
        SERVICE_NAME = 'service-a'
        REGISTRY = 'localhost:5000'
        IMAGE_REPO = "${REGISTRY}/service-a"

        DEV_PORT  = '18081'
        PROD_PORT = '28081'

        DEV_CONTAINER  = 'service-a-dev'
        PROD_CONTAINER = 'service-a-prod'
    }

    stages {
        stage('Init') {
            steps {
                echo "Pipeline started"
                echo "Branch = ${env.BRANCH_NAME}"
            }
        }

        stage('Check Tools') {
            steps {
                sh 'git --version'
                sh 'mvn -version'
                sh 'docker --version'
                sh 'docker compose version'
            }
        }

        stage('Maven Test') {
            steps {
                dir('service-a') {
                    sh 'mvn clean test'
                }
            }
        }

        stage('SonarQube Scan') {
            steps {
                dir('service-a') {
                    withSonarQubeEnv('sonarqube-local') {
                        sh '''
                            mvn sonar:sonar \
                              -Dsonar.projectKey=service-a \
                              -Dsonar.projectName=service-a
                        '''
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Maven Package') {
            steps {
                dir('service-a') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('service-a') {
                    sh 'docker build -t service-a:ci-${BUILD_NUMBER} .'
                }
            }
        }
		
		stage('Trivy Report') {
			steps {
				dir('service-a') {
					sh '''
						docker run --rm \
						  -v /var/run/docker.sock:/var/run/docker.sock \
						  -v trivy_cache:/root/.cache/ \
						  aquasec/trivy:0.62.0 image \
						  --scanners vuln \
						  --severity HIGH,CRITICAL \
						  --ignore-unfixed \
						  --no-progress \
						  --format table \
						  --exit-code 0 \
						  service-a:ci-${BUILD_NUMBER} \
						  > trivy-image-report.txt
					'''
					sh 'ls -la'
					sh 'test -f trivy-image-report.txt'
				}
			}
		}

        stage('Push Registry') {
            steps {
                script {
                    if (env.BRANCH_NAME == 'develop') {
                        sh '''
                            docker tag service-a:ci-${BUILD_NUMBER} ${IMAGE_REPO}:dev-latest
                            docker push ${IMAGE_REPO}:dev-latest
                        '''
                    } else if (env.BRANCH_NAME == 'main') {
                        sh '''
                            docker tag service-a:ci-${BUILD_NUMBER} ${IMAGE_REPO}:prod-latest
                            docker push ${IMAGE_REPO}:prod-latest
                        '''
                    } else {
                        echo "Skip push: unsupported branch ${env.BRANCH_NAME}"
                    }
                }
            }
        }

        stage('Deploy Dev') {
            when {
                branch 'develop'
            }
            steps {
                sh '''
                    docker rm -f ${DEV_CONTAINER} || true

                    docker run -d \
                      --name ${DEV_CONTAINER} \
                      -p ${DEV_PORT}:8080 \
                      ${IMAGE_REPO}:dev-latest
                '''
            }
        }

        stage('Verify Dev') {
            when {
                branch 'develop'
            }
            steps {
                sh '''
                    sleep 10
                    curl -f http://host.docker.internal:${DEV_PORT}/hello
                    curl -f http://host.docker.internal:${DEV_PORT}/actuator/health
                '''
            }
        }
		
		stage('OWASP ZAP Baseline Scan') {
			when {
				branch 'develop'
			}
			steps {
				dir('service-a') {
					sh '''
						docker run --rm \
						  -u root \
						  --network host \
						  -v "$PWD:/zap/wrk" \
						  owasp/zap2docker-stable zap-baseline.py \
						  -t http://host.docker.internal:18081 \
						  -J zap-report-dev.json \
						  -r zap-report-dev.html \
						  -I
					'''
					sh 'ls -la'
					sh 'test -f zap-report-dev.html'
					sh 'test -f zap-report-dev.json'
				}
			}
		}

        stage('Deploy Prod') {
            when {
                branch 'main'
            }
            steps {
                sh '''
                    docker rm -f ${PROD_CONTAINER} || true

                    docker run -d \
                      --name ${PROD_CONTAINER} \
                      -p ${PROD_PORT}:8080 \
                      ${IMAGE_REPO}:prod-latest
                '''
            }
        }

        stage('Verify Prod') {
            when {
                branch 'main'
            }
            steps {
                sh '''
                    sleep 10
                    curl -f http://host.docker.internal:${PROD_PORT}/hello
                    curl -f http://host.docker.internal:${PROD_PORT}/actuator/health
                '''
            }
        }
    }
	
	post {
		always {
			archiveArtifacts artifacts: 'service-a/trivy-image-report.txt, service-a/zap-report-dev.html, service-a/zap-report-dev.json', fingerprint: true
		}
	}
}