pipeline {
    agent any

    environment {
        SERVICE_NAME = 'service-b'
        REGISTRY = 'localhost:5000'
        IMAGE_REPO = "${REGISTRY}/service-b"

        DEV_PORT  = '18082'
        PROD_PORT = '28082'

        DEV_CONTAINER  = 'service-b-dev'
        PROD_CONTAINER = 'service-b-prod'
    }

    stages {
        stage('Init') {
            steps {
                echo "Pipeline started"
                echo "Branch = ${env.BRANCH_NAME}"
            }
        }

        stage('Check Tools') {
            steps {
                sh 'git --version'
                sh 'mvn -version'
                sh 'docker --version'
                sh 'docker compose version'
            }
        }

        stage('Maven Test') {
            steps {
                dir('service-b') {
                    sh 'mvn clean test'
                }
            }
        }

        stage('SonarQube Scan') {
            steps {
                dir('service-b') {
                    withSonarQubeEnv('sonarqube-local') {
                        sh '''
                            mvn sonar:sonar \
                              -Dsonar.projectKey=service-b \
                              -Dsonar.projectName=service-b
                        '''
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Maven Package') {
            steps {
                dir('service-b') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('service-b') {
                    sh 'docker build -t service-b:ci-${BUILD_NUMBER} .'
                }
            }
        }
		
		stage('Trivy Report') {
			steps {
				dir('service-b') {
					sh '''
						docker run --rm \
						  -v /var/run/docker.sock:/var/run/docker.sock \
						  -v trivy_cache:/root/.cache/ \
						  aquasec/trivy:0.62.0 image \
						  --scanners vuln \
						  --severity HIGH,CRITICAL \
						  --ignore-unfixed \
						  --no-progress \
						  --format table \
						  --exit-code 0 \
						  service-b:ci-${BUILD_NUMBER} \
						  > trivy-image-report.txt
					'''
					sh 'ls -la'
					sh 'test -f trivy-image-report.txt'
				}
			}
		}

        stage('Push Registry') {
            steps {
                script {
                    if (env.BRANCH_NAME == 'develop') {
                        sh '''
                            docker tag service-b:ci-${BUILD_NUMBER} ${IMAGE_REPO}:dev-latest
                            docker push ${IMAGE_REPO}:dev-latest
                        '''
                    } else if (env.BRANCH_NAME == 'main') {
                        sh '''
                            docker tag service-b:ci-${BUILD_NUMBER} ${IMAGE_REPO}:prod-latest
                            docker push ${IMAGE_REPO}:prod-latest
                        '''
                    } else {
                        echo "Skip push: unsupported branch ${env.BRANCH_NAME}"
                    }
                }
            }
        }

        stage('Deploy Dev') {
            when {
                branch 'develop'
            }
            steps {
                sh '''
                    docker rm -f ${DEV_CONTAINER} || true

                    docker run -d \
                      --name ${DEV_CONTAINER} \
                      -p ${DEV_PORT}:8080 \
                      ${IMAGE_REPO}:dev-latest
                '''
            }
        }

        stage('Verify Dev') {
            when {
                branch 'develop'
            }
            steps {
                sh '''
                    sleep 10
                    curl -f http://host.docker.internal:${DEV_PORT}/hello
                    curl -f http://host.docker.internal:${DEV_PORT}/actuator/health
                '''
            }
        }

        stage('Deploy Prod') {
            when {
                branch 'main'
            }
            steps {
                sh '''
                    docker rm -f ${PROD_CONTAINER} || true

                    docker run -d \
                      --name ${PROD_CONTAINER} \
                      -p ${PROD_PORT}:8080 \
                      ${IMAGE_REPO}:prod-latest
                '''
            }
        }

        stage('Verify Prod') {
            when {
                branch 'main'
            }
            steps {
                sh '''
                    sleep 10
                    curl -f http://host.docker.internal:${PROD_PORT}/hello
                    curl -f http://host.docker.internal:${PROD_PORT}/actuator/health
                '''
            }
        }
		
		stage('OWASP ZAP Baseline Scan') {
			steps {
				script {
					if (env.BRANCH_NAME == 'develop') {
						dir('service-a') {
							sh '''
								rm -f zap-report-dev.html zap-report-dev.json || true
								docker rm -f zap-service-a-dev-scan || true

								docker create --name zap-service-a-dev-scan \
								  --network host \
								  zaproxy/zap-stable \
								  sh -c "mkdir -p /zap/wrk && zap-baseline.py -t http://host.docker.internal:18081 -r zap-report-dev.html -J zap-report-dev.json -I"

								docker start -a zap-service-a-dev-scan
								docker cp zap-service-a-dev-scan:/zap/wrk/zap-report-dev.html ./zap-report-dev.html
								docker cp zap-service-a-dev-scan:/zap/wrk/zap-report-dev.json ./zap-report-dev.json
								docker rm -f zap-service-a-dev-scan || true

								ls -la
								test -f zap-report-dev.html
								test -f zap-report-dev.json
							'''
						}
					} else if (env.BRANCH_NAME == 'main') {
						dir('service-a') {
							sh '''
								rm -f zap-report-prod.html zap-report-prod.json || true
								docker rm -f zap-service-a-prod-scan || true

								docker create --name zap-service-a-prod-scan \
								  --network host \
								  zaproxy/zap-stable \
								  sh -c "mkdir -p /zap/wrk && zap-baseline.py -t http://host.docker.internal:28081 -r zap-report-prod.html -J zap-report-prod.json -I"

								docker start -a zap-service-a-prod-scan
								docker cp zap-service-a-prod-scan:/zap/wrk/zap-report-prod.html ./zap-report-prod.html
								docker cp zap-service-a-prod-scan:/zap/wrk/zap-report-prod.json ./zap-report-prod.json
								docker rm -f zap-service-a-prod-scan || true

								ls -la
								test -f zap-report-prod.html
								test -f zap-report-prod.json
							'''
						}
					} else {
						echo "Skip ZAP scan for branch ${env.BRANCH_NAME}"
					}
				}
			}
		}
		
    }
	
	post {
		always {
			archiveArtifacts artifacts: 'service-a/trivy-image-report.txt, service-a/zap-report-dev.html, service-a/zap-report-dev.json, service-a/zap-report-prod.html, service-a/zap-report-prod.json', fingerprint: true
		}
	}
}